name: 'Upload Microsoft Store MSIX Package to GitHub Release'
description: 'Download MSIX package from Microsoft Store and upload to GitHub release.'
branding:
  icon: upload
  color: blue


inputs:
  store-id:
    description:
      'The ID of the Microsoft Store app you want to upload, e.g. "9NF7JTB3B17P".'
    required: true

  token:
    description:
      'The GitHub token to use.'
    required: true

  asset-name-pattern:
    description: |
      The pattern of the uploaded GitHub release asset's name without file extension. Can contain "{version}" and "{arch}". 
      For example, for pattern "AppName_{version}_{arch}", the uploaded asset's name can be "AppName_1.2.3.0_x64.Msix".
    required: false
    default: ''


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '--store-id'
  - ${{ inputs.store-id }}
  - '--token'
  - ${{ inputs.token }}
  - '--asset-name-pattern'
  - ${{ inputs.asset-name-pattern }}