name: 'Upload Microsoft Store Msix Package to GitHub Release'
description: 'Download Msix package from Microsoft Store and upload to GitHub release.'
branding:
  icon: activity
  color: orange


inputs:
  store-id:
    description:
      'The ID of the Microsoft Store app you want to upload, e.g. "9N0DX20HK701".'
    required: true

  token:
    description:
      'The GitHub token to use.'
    required: true

  asset-name-pattern:
    description: |
      The name pattern of the uploaded GitHub release asset's name without file extension. Can contain "{version}" and "{arch}". 
      For example, for pattern "App_{version}_{arch}", the uploaded asset name can be "App_1.2.3.0_x64.Msix".
    required: false
    default: ''


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '--store-id'
  - ${{ inputs.store-id }}
  - '--token'
  - ${{ inputs.token }}
  - '--asset-name-pattern'
  - ${{ inputs.asset-name-pattern }}